### ISSUE TITLE
Replace type imports with generics?

### ISSUE THREAD

**Issue by jamiehodge** [graphql-nexus/schema#355]
I don't understand why it isn't possible to let object types take a second type parameter that specifies the backing type, i.e. `objectType<"Foo", Foo>`. Additionally, why can't makeSchema become `makeSchema<Context>`?

I feel as though nexus is reimplementing quite a lot of type-level logic to support the sources approach when a generic might suffice.

This is, in any case, the approach of this module: https://github.com/sikanhe/gqtx

**Comment by tgriesser** [comment]
A lot of the original design decision centered around being able to specify the types as strings rather than as object references, both to guard against circular imports and to allow for dynamic field creation via plugins. See https://github.com/prisma-labs/nexus/issues/5#issuecomment-451221568 for more info.

Hindsight being 20/20, there are probably still ways to do this that involve simpler/more immediate type inference, even retaining the typename via string reference a design goal, e.g. by only keeping a lookup map of the "backing types".

I think there are some gaps in the lib you linked (which looks pretty cool by the way). For instance, the fact that `Ctx = null` in the generics [here](https://github.com/sikanhe/gqtx/blob/cd090c45baf5fbb558ddab0eb6bd95accf58fffa/src/define.ts#L169-L175) means that you'll need to provide it in all cases in order to get it in the resolver, it won't be inferred automatically, the `makeSchema<Context>` will not bubble forward to any usage in in `objectType` or elsewhere.

Some this relates to https://github.com/microsoft/TypeScript/issues/10571, that if you specify some of the generics you need but not all of them, they won't be inferred by usage. 

That said, I think there are opportunities to simplify some of Nexus' internals closer to the module you linked. I had recently come to the realization that the approaches we take around nullability and lists should probably map closer to `graphql-js`, which would allow for type wrapping/unwrapping in a way that would require less type-lookup to work properly.

```ts
t.field('role', { 
  type: t.List(t.NonNull(MembershipRole))
})
```

or

```ts
t.field('role', { 
  type: t.List(t.NonNull('MembershipRole'))
})
```

It'll be quite a bit change, so the implications/migration path need to be thought about a bit more before doing so. I've been planning on doing a deep dive into better refining the type generation process - having flexibility there may help influence some the potential changes here.

**Comment by jasonkuhrt** [comment]
Hey @jamiehodge, good question. If you had dozens or hundreds of graphql objects in your schema, how would you feel about being required to import backing types and threading them through every object type def?

There is also a benefit where a plugin can provide backing type information. For example with the Prisma plugin it makes sense to use photon types (representing models in your data layer) as the backing types. What do you think about if you had to manually import and thread through those types from Photon?

This is not an authoritative or exhaustive answer. Just getting the ball rolling. On mobile right now.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jamiehodge** [comment]
Thank you for the considered answers/questions.

I know from experience with graphql.js that circular dependencies can prove problematic and hard to debug. Having said that, it is easier to reason about, save for the cryptic errors when there are circular dependencies.

I guess you would need to specify the Context for each generic, but it does scare me that I can currently lie to nexus about what context type I eventually pass to it. Couldn't this issue be mitigated by "currying" the generics?

Given the current solution, is there any possibility that one could directly reference types in the makeSchema backing types map instead of referring to a file? I noticed the other day that the current solution complicates bundling with tools like ncc, as you still have references to `.ts` files in your production bundle.

**Comment by jamiehodge** [comment]
Another thought was that the current, generated types could be defaults for optionally set generics.

**Comment by jasonkuhrt** [comment]
Yeah generated as fallback type value would be elegant.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sikanhe** [comment]
We have an incoming PR to let you specify `Context` type for the entire schema type creators, do you only ever need to specify context type once: https://github.com/sikanhe/gqtx/pull/7

**Comment by jasonkuhrt** [comment]
@sikanhe cool project. Nexus Schema has a pure static design with regard to type builders. There is no notion of a factory that returns methods with some state shared between them (type or term level).

Nexus Framework is not pure. It has term level state wherein return values from all calls build up internal schema state. In theory we could:

- Add a Context generic to all Nexus Schema builders
- Add a Context generic to the NexusSchemaSingleton which it forwards to all the Nexus Schema builders

One way for a developer to pass the Context generic would be via a global augmentation e.g.:

```ts
declare global {
  interface NexusContext {
    // ...
  }
}
```

Actually this could apply to either Nexus Framework or Nexus Schema––but having this at the level of Nexus Schema would be a bigger mental shift (again, they are currently pure).

If Nexus Framework were changed so users create the singleton themselves, rather than it being handed from an import, then the global augmentation system wouldn't be needed, it could be a matter of:

```ts
const schema = createSchema<WhateverContext>()
```

Anyways I'm just riffing here. Nexus Framework relies on AST analysis of term-level code `schema.addToContext(req => { ...` so users don't need to think about this anyways. I think we're pretty happy with that approach. But also I think we're open to generics with defaults as has already been mentioned above.
