### ISSUE TITLE
t.connectionField requiring a first or last argument

### ISSUE THREAD

**Issue by blazestudios23** [graphql-nexus/schema#401]
I have a 
t.connectionField()
inside another type, so it is already filtering by the parent types ID, however I get the following error:

`"message": "The parentType.childType connection field requires a \"first\" or \"last\" argument"`

These do not show up as required in the schema and making it required is not useful for a child type in any way. If users want to make fields required then they should do so themselves, but this should not be default behavior.

**Comment by dpekkle** [comment]
FYI that behaviour is part of the Connections specification

> A field that returns a Connection Type must include forward pagination arguments, backward pagination arguments, or both. These pagination arguments allow the client to slice the set of edges before it is returned.

https://facebook.github.io/relay/graphql/connections.htm#sel-EAJDABIBN0uX

You are free to pass filters in, but if you do not want a child field to be paginated then using a connection may not be the best approach. 

As for them not showing up as required, I imagine it is because none of the pagination arguments individually are always required, but at least one set must be (forward || backward).

If you are wanting a connection as you are trying to make available information such as a total count then an alternative wrapper may be the best bet, or by placing the total count on the parent. There may also be ways to alter the behaviour of connections in your implementation, but I think it should be clear going against the spec shouldn't be default behaviour.

**Comment by tgriesser** [comment]
> that behaviour is part of the Connections specification

Yep, as @dpekkle - this is the reason we require this by default. You can also configure the validation by passing a custom `validateArgs` function to the connection plugin config: 

https://nexus.js.org/docs/plugin-connection#argument-validation

**Comment by blazestudios23** [comment]
Hey thanks, in my use case there are not more than a few items in the connections, but if there's a way to auto pass in the before I would love to know. 

There's isn't an example in the link of what actually goes in the validation function. So how would I say to ignore these values?

**Comment by tgriesser** [comment]
> Hey thanks, in my use case there are not more than a few items in the connections, but if there's a way to auto pass in the before I would love to know.

I'm not sure if this is what you're asking, but one option is to make it not-explicitly required would be to set a very high default value for `first`:

```ts
connectionPlugin({
  additionalArgs: intArg({ default: 2147483647 })
})

```

> There's isn't an example in the link of what actually goes in the validation function. So how would I say to ignore these values?

Basically as long as you don't throw, it'll ignore the values. See the [default implementation](https://github.com/graphql-nexus/schema/blob/ccae81ab6e433e2f378ffb721eae3198a20412e5/src/plugins/connectionPlugin.ts#L996-L1020)

**Comment by blazestudios23** [comment]
That causes the following Error: 
```

- Missing type undefined, did you forget to import a type to the root query?
- Missing type [object Object], did you forget to import a type to the root query?
```
