### ISSUE TITLE
Include only partial fields

### ISSUE THREAD

**Issue by ryands17** [graphql-nexus/schema#431]
What would be the best way to create a resolver to select specific fields from a model in Prisma?

Currently I have the following query and I want to select only specific fields from the `User` model.

```graphql
query users {
  all {
    id
    name
  }
}
```

On trying to create the same in Nexus, I create the resolver as follows:

```ts
export const users = queryField('users', {
  type: 'User',
  list: true,
  resolve(_parent, _args, ctx) {
    return ctx.prisma.user.findMany({
      select: {
        id: true,
        name: true
      }
    })
  },
})
```

On creating this, TS throws the following error:

```
Type 'Promise<{ id: number; name: string; }[]>' is not assignable to type 'User[]
```

Would it be possible to augment the `User` type to only include partial fields? It would be helpful for perf reasons as well.

**Comment by Sytten** [comment]
Usually you need to convert the info parameter (the fourth one) into a dictionary. Something similar to what https://paljs.com/plugins/select/ does. I believe that since it most likely won't be able to resolve the select, it will default to the full object and so the typing will accept it. It is a bit of "hack" in a sense that you do not really have the full object. So if a children resolver needs some information from the parent, it might not be available and so I generally don't like this technique.

**Comment by ryands17** [comment]
@Sytten but wound't it be inefficient to query all fields when only 1-2 are required?

**Comment by Sytten** [comment]
Honestly unless your connection between your backend and database is slow it doesn't make a big difference. Look at Shopify, they use rails with active record (meaning the whole record is pulled all the time) and they scale like crazy. So thats why I always call BS of this optimization. At worst you use a dataloader and be done with it.

**Comment by Weakky** [comment]
Fully agrees with Sytten here, although there are some rare cases where this optimization can make sense. Nonetheless, I think we can close this issue as it's been answered anyway.

Keep in mind though that this will basically mess your type-safety as you'll no longer have any guarantee about what field will be passed down to your children resolvers unless you add default fields when converting the `info` parameters. Regardless, it means you'll have to create manual backing types so that it reflects properly exactly what's being passed down.

Closing now 👍
