### ISSUE TITLE
`t.list.field` doesn't obey `nonNullDefaults`

### ISSUE THREAD

**Issue by migueloller** [graphql-nexus/schema#588]
The following definition will result in the subsequent schema with `nonNullDefaults` set to `{ output: true, input: true }`:
```typescript
queryType({
  definition(t) {
    t.list.int('ints')
  }
})
```
```graphql
type Query {
  ints: [Int]!
}
```

Instead, [according to the documentation](https://nexusjs.org/docs/guides/schema#lists-and-nullability), it should result in this schema:
```graphql
type Query {
  ints: [Int!]!
}
```

The alternative is not as ergonomic:
```typescript
queryType({
  definition(t) {
    t.int('ints', { list: [true] })
  }
})
```

**Comment by cypcz** [comment]
I just ran into this today as well. Upgraded to the latest version, generated types and boom, FE code is broken because it doesn't handle possible null values.

Also according to the [docs](https://nexusjs.org/docs/api/make-schema#nonnulldefaults), Nexus current default for `nonNullDefaults` is `{ output: true, input: false }`. However:
- using default setting by omitting it in the config results in `[String]`
- using the said default `{ output: true, input: false }` in the config results in `[String]!`

Please, give us back `[String!]!`.

**Comment by tgriesser** [comment]
Yeah, just ran into this as well. Will work on a fix for this.

**Comment by migueloller** [comment]
@tgriesser, thanks for the prompt response and fix!
